apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gradio-ui
  namespace: openshift-gitops
spec:
  destination:
    namespace: llms
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ui/overlays/
    repoURL: https://github.com/gsampaio-rh/hftgi-llms
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

